# Generated by Django 5.1.7 on 2025-03-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_lesson_options_course_timestamp_course_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='public_id',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
