# Generated by Django 5.1.7 on 2025-03-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='public_id',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
