# Generated by Django 6.0.3 on 2026-04-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_public_id_alter_lesson_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('soon', 'Coming Soon'), ('ongoing', 'Ongoing'), ('draft', 'Draft')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('soon', 'Coming Soon'), ('ongoing', 'Ongoing'), ('draft', 'Draft')], default='ongoing', max_length=10),
        ),
    ]
