# Generated by Django 6.0.3 on 2026-04-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_status_alter_lesson_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='access',
            field=models.CharField(choices=[('any', 'Anyone'), ('enrolled', 'Enrolled')], default='enrolled', max_length=20),
        ),
    ]
