# Generated by Django 5.1.7 on 2025-03-23 12:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_email_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationevent',
            name='token',
            field=models.UUIDField(default=uuid.UUID('fa4f77ea-07de-11f0-a7cb-90324b76e1ee')),
        ),
    ]
